# Generated by Django 3.2.3 on 2022-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_configuration_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
