# Generated by Django 3.2.3 on 2022-05-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_owner_id_configuration_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
